# Generated by Django 5.2.4 on 2025-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Alphabet',
                'verbose_name_plural': 'Alphabets',
            },
        ),
        migrations.CreateModel(
            name='NaturalNumber',
            fields=[
                ('id', models.PositiveBigIntegerField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Natural Number',
                'verbose_name_plural': 'Natural Numbers',
            },
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Username',
                'verbose_name_plural': 'Usernames',
            },
        ),
    ]
