# Generated by Django 5.2.4 on 2025-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangouniquetoolkit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
